### PR TITLE
There can be license-specific output lines before parameters (e.g., WLS)

### PR DESCRIPTION
**Pull request by ruthmair**
This doctest fails with a WLS license.

### CODE REVIEW

**Comment by ruthmair** [comment]
Hmm, without WLS the fix fails again. I thought that "..." includes no line, obviously not.

**Comment by ruthmair** [comment]
please note that only the first commit is relevant for this issue.

**Comment by simonbowly** [comment]
> Hmm, without WLS the fix fails again. I thought that "..." includes no line, obviously not.

Yes it's annoying finnicky that ellipsis can't match nothing. I couldn't find a way around yet, but surely there's an option we're missing.

**Comment by ruthmair** [comment]
I did a quick search but found nothing. closing this PR for now until we found a useful solution.

**Pull request closed without merging**
