### PR TITLE
Implement optimal power flow

### PR DESCRIPTION
**Pull request by simonbowly**
### Description

OPF optimod. Continues #43.

### Checklist

- Implementation:
  - [x] Implementation of the Mod in the `gurobi_optimods` installable package
  - [x] Tests for the Mod implementation in `tests/`
  - [x] Docstrings for public API, correctly linked using sphinx-autodoc
- Documentation page:
  - [x] Background and problem specification
  - [x] Example of the input data format (use `gurobi_optimods.datasets` for loading data)
  - [x] Runnable code example
  - [x] Presentation of solutions
  - [x] Included in the mod gallery and toctree

**Have a nice day!**

### CODE REVIEW

**Comment by simonbowly** [comment]
Still to do in the code:

- [ ] `TestOpf.test_settings` isn't fit for CI, needs to be cut down to a more reasonable set to be useful. It also seems to be dependent on a parameter file.
- [ ] Clean up dead code like `opf.grbformulator.writemipstart`
- [ ] Get rid of "gurobiparamfile", solver parameters are better off being handled using optimods infrastructure
- [ ] Find and fix unsafe function definitions like this one in solve_opf_model:

```python
def solve_opf_model(..., additional_settings=dict())
```

Still to do in the docs:

- [ ] Link to API reference, update API docstrings to numpydoc style
- [ ] ACOPF/DCOPF pages still contain template sentences
- [ ] Main docs page needs background. The current structure is terminology -> references -> mat.
- [ ] Solutions need to be presented in the docs
- [ ] Other API functions need to be demo'd in the docs, so far only solve_opf_model is shown

**Comment by simonbowly** [comment]
@JaromilNajman does the `useef` option currently do anything? It doesn't seem to be implemented. Also, does `ivtype` affect only the IV formulation?

**Comment by simonbowly** [comment]
@JaromilNajman for branches, buses, and generators the dict format looks like this:

```
{
    "bus": {
        1: {...},
        2: {...},
    }
}
```

however all the reader routines can only handle the case where the dictionary keys are `1..n`. It cannot even handle the case where those keys are out of order, as it assumes this order in most cases.

So the keys are just a source of user errors and don't provide any useful information. I'd like to change the format to a list of dicts, i.e.:

```
{
    "bus": [
        {... data for bus 1 ...},
        {... data for bus 2 ...},
    ],
}
```

would this cause issues elsewhere?

**Comment by simonbowly** [comment]
> The only issue I see is that when we read something like this in and then return the solution dictionary, then the names of the indices are different.

Yes this is my point. It's very hard for users to relate solutions to their inputs if the keys do not align. As a user I should also be able to re-order the keys in a dictionary and expect the same result, and this is not possible in the current code.

**Comment by simonbowly** [comment]
Docs are looking good so far, I have a few high-level comments/questions from a first pass:

- In 'Problem Specification' notation is introduced which is not used anywhere else on the page. I suggest moving this  to a different page (along with the ACOPF/DCOPF details) and just giving a link to it here. This section could then be replaced with a diagram outlining a simple network.
- It might be better move the details of reading a case to a later point, and condense the 'Input' section a little bit. We should also think about transparently handling both formats as we do with other mods, then we could avoid all the discussion of convenience functions.
- In 'Graphical Representation' can we link to these other tools? And would it be easy to convert outputs from the mod for use with those tools?
- Is there any equivalent in the MATPOWER spec for coordinates or voltages?

**Comment by JaromilNajman** [comment]
>In 'Problem Specification' notation is introduced which is not used anywhere else on the page. I suggest moving this to a different page (along with the ACOPF/DCOPF details) and just giving a link to it here. This section could then be replaced with a diagram outlining a simple network.

Ok, makes sense.

>It might be better move the details of reading a case to a later point, and condense the 'Input' section a little bit. We should also think about transparently handling both formats as we do with other mods, then we could avoid all the discussion of convenience functions.

We should discuss this one.

>In 'Graphical Representation' can we link to these other tools? And would it be easy to convert outputs from the mod for use with those tools?

Sure, we can. Every tool has their own format for this. MATPOWER has special functions but they use the case format, so this would be easy as you could just use the function to generate a .mat file. PyPSA, panda power and pypower all havee their own data structures so this would not be so easy. I don't think that we should aim to provide any of those. The industry does not use open-source packages but rather has their own tailored plotting tools.

>Is there any equivalent in the MATPOWER spec for coordinates or voltages?

I did not find any. The MATPOWER function seems to automatically compute a visually nice layout for the network. However, there are extensions where you can additionally provide coordinates. The violations function is not present in MATPOWER. This is really something that only we have compared to other packages.

**Comment by JaromilNajman** [comment]
@simonbowly I reworked the docs quite a bit. Please have a look.

**Pull request merged**
